# Generated by Django 3.0.5 on 2020-04-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200423_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.TextField(default='flat'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.TextField(default='object'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
