# Generated by Django 3.0.5 on 2020-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200424_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Hall', 'Hall'), ('Bathroom', 'Bathroom'), ('Toilet', 'Toilet')], default='Kitchen', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Hat', 'Hat'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Shirt', 'Shirt')], default='Shoes', max_length=100),
        ),
    ]
