# Generated by Django 3.0.5 on 2020-04-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='position',
            new_name='position_layout',
        ),
        migrations.RemoveField(
            model_name='item',
            name='place',
        ),
        migrations.AddField(
            model_name='item',
            name='position_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_layout+', to='main.Layout'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Blouse', 'Blouse'), ('Skirt', 'Skirt'), ('Shirt', 'Shirt'), ('Accessory', 'Accessory'), ('Hat', 'Hat'), ('T-shirt', 'T-shirt')], default='Shoes', max_length=100),
        ),
        migrations.AlterField(
            model_name='layout',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
