# Generated by Django 3.0.5 on 2020-04-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200427_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='author',
            new_name='user',
        ),
    ]
