# Generated by Django 3.0.5 on 2020-05-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200427_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(default='No details'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='No size', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='position_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_layout+', to='main.Layout', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Accessory', 'Accessory'), ('Blouse', 'Blouse'), ('Boots', 'Boots'), ('Coat', 'Coat'), ('Hat', 'Hat'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Kitchenware', 'Kitchenware'), ('Overcoat', 'Overcoat'), ('Pants', 'Pants'), ('Polo-shirt', 'Polo-shirt'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Skirt', 'Skirt'), ('Socks', 'Socks'), ('Sweater', 'Sweater'), ('T-shirt', 'T-shirt'), ('Tie', 'Tie'), ('Underwear', 'Underwear'), ('instrument', 'Instrument'), ('Other', 'Other')], default='Shoes', max_length=100),
        ),
        migrations.AlterField(
            model_name='layout',
            name='position_layout',
            field=models.CharField(default='No location', max_length=100),
        ),
    ]
