# Generated by Django 3.0.5 on 2020-04-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200427_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='position_item',
            field=models.ForeignKey(default='No Location is Set', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='position_layout+', to='main.Layout'),
        ),
    ]
