# Generated by Django 3.0.5 on 2020-04-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200427_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='position_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_layout+', to='main.Layout', verbose_name='Location'),
        ),
    ]
