# Generated by Django 3.0.5 on 2020-04-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200427_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='position_layout',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
