# Generated by Django 3.0.5 on 2020-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200428_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='position_layout',
            field=models.CharField(default='No location', max_length=100, unique=True),
        ),
    ]
