# Generated by Django 3.0.5 on 2020-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200428_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.TextField(default='No details'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='No size', max_length=100),
        ),
    ]
