# Generated by Django 3.0.5 on 2020-04-26 07:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='infrastructure',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Kitchen', 'Kitchen'), ('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Hall', 'Hall'), ('Bathroom', 'Bathroom'), ('Toilet', 'Toilet'), ('Bedroom', 'Bedroom'), ('Bedroom 2', 'Bedroom 2'), ('Bedroom 3', 'Bedroom 3'), ('Balcony', 'Balcony')], default=[('Kitchen', 'Kitchen'), ('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Hall', 'Hall'), ('Bathroom', 'Bathroom'), ('Toilet', 'Toilet'), ('Bedroom', 'Bedroom'), ('Bedroom 2', 'Bedroom 2'), ('Bedroom 3', 'Bedroom 3'), ('Balcony', 'Balcony')], max_length=78),
        ),
    ]
