# Generated by Django 3.0.5 on 2020-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_infrastructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='infrastructure',
            field=models.TextField(default=''),
        ),
    ]
