# Generated by Django 3.0.5 on 2020-04-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200426_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='infrastructure',
        ),
    ]
