# Generated by Django 3.0.5 on 2020-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
