# Generated by Django 3.0.5 on 2020-04-27 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20200427_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='user',
        ),
        migrations.AddField(
            model_name='layout',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
